---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "rscriptannotate"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "rscriptannotate":
      ## TODO nf-core: Add a description and other details for the software below
      description: "R is a free software environment for statistical computing and graphics."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ['GPL v2-or-later']
      identifier:

## TODO nf-core: Add a description of all of the variables used as input
input:
  - - rscript:
        type: file
        description: R script file
        pattern: "*.R"
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - vcf:
        type: file
        description: VCF file
        pattern: "*.{vcf,vcf.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_3016"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - bed:
        type: file
        description: BED file
        pattern: "*.bed"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - bim:
        type: file
        description: BIM file
        pattern: "*.bim"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - fam:
        type: file
        description: FAM file
        pattern: "*.fam"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - bgen:
        type: file
        description: BGEN file
        pattern: "*.bgen"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - bgen_bgi:
        type: file
        description: BGEN.BGI file
        pattern: "*.bgen.bgi"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - sample:
        type: file
        description: SAMPLE file
        pattern: "*.sample"


## TODO nf-core: Add a description of all of the variables used as output
output:
  - phenotype:
  #Only when we have meta
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  ## TODO nf-core: Delete / customise this example output
    - "*_phenotype.txt":
        type: file
        description: phenotype file
        pattern: "*_phenotype.txt"

  - annotations:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      ## TODO nf-core: Delete / customise this example output
      - "*.annotations":
          type: file
          description: annotations file
          pattern: "*.annotations"

  - masks:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      ## TODO nf-core: Delete / customise this example output
      - "*.masks":
          type: file
          description: masks file
          pattern: "*.masks"

  - setlist:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      ## TODO nf-core: Delete / customise this example output
      - "*.setlist":
          type: file
          description: setlist file
          pattern: "*.setlist"

  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@psuszyns"
maintainers:
  - "@psuszyns"
