---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bgenix"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "bgenix":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Reference implementation of the BGEN format, written in C++"
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ['BSL-1.0']
      identifier:

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

  ## TODO nf-core: Delete / customise this example input
    - bgen:
        type: file
        description: BGEN file
        pattern: "*.bgen"


## TODO nf-core: Add a description of all of the variables used as output
output:
  - bgen_bgi:
  #Only when we have meta
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  ## TODO nf-core: Delete / customise this example output
    - "*.bgen.bgi":
        type: file
        description: bgen.bgi file
        pattern: "*.bgen.bgi"

  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@psuszyns"
maintainers:
  - "@psuszyns"
