---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "rename"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "rename":
      ## TODO nf-core: Add a description and other details for the software below
      description: "R is a free software environment for statistical computing and graphics."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ['GPL v2-or-later']
      identifier:

input:
  - - input_file:
        type: file
        description: input file

  - - output_file_name:
        type: string
        description: |
          output file name

output:
  - phenotype:
    - "${output_file_name}":
        type: file
        description: output file

authors:
  - "@psuszyns"
maintainers:
  - "@psuszyns"
