---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "rscriptvcftoaaf"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "rscriptvcftoaaf":
      ## TODO nf-core: Add a description and other details for the software below
      description: "R is a free software environment for statistical computing and graphics."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ['GPL v2-or-later']
      identifier:

## TODO nf-core: Add a description of all of the variables used as input
input:
  - - rscript:
        type: file
        description: R script file
        pattern: "*.R"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - masks_snplist:
        type: file
        description: masks_snplist file
        pattern: "*_masks.snplist"
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - y1_regenie:
        type: file
        description: y1_regenie file
        pattern: "*_Y1.regenie"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - vcf:
        type: file
        description: VCF file
        pattern: "*.{vcf,vcf.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_3016"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - phenotype:
        type: file
        description: phenotype file
        pattern: "*_phenotype.txt"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - annotations:
        type: file
        description: annotations file
        pattern: "*.annotations"


## TODO nf-core: Add a description of all of the variables used as output
output:
  - annotated_snps:
  #Only when we have meta
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  ## TODO nf-core: Delete / customise this example output
    - "*_annotated_snps.tsv":
        type: file
        description: annotated_snps file
        pattern: "*_annotated_snps.tsv"
  - res_log10p_1_annotated:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      ## TODO nf-core: Delete / customise this example output
      - "*_res_log10p_1_annotated.tsv":
          type: file
          description: _es_log10p_1_annotated file
          pattern: "*_res_log10p_1_annotated.tsv"
  - annotated_snps_with_sample_ids:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      ## TODO nf-core: Delete / customise this example output
      - "*_annotated_snps_with_sample_ids.tsv":
          type: file
          description: annotated_snps_with_sample_ids file
          pattern: "*_annotated_snps_with_sample_ids.tsv"

  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@psuszyns"
maintainers:
  - "@psuszyns"
