---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "plink19makebed"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "plink19makebed":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ['GPL']
      identifier:

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - vcf:
        type: file
        description: VCF file
        pattern: "*.{vcf,vcf.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_3016"


## TODO nf-core: Add a description of all of the variables used as output
output:
  - bed:
  #Only when we have meta
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - "*.bed":
        type: file
        description: BED file
        pattern: "*.{bed}"
        ontologies:
          - edam: "http://edamontology.org/format_3003"

  - bim:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.bim":
          type: file
          description: BIM file
          pattern: "*.{bim}"

  - fam:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.fam":
          type: file
          description: FAM file
          pattern: "*.{fam}"

  - nosex:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.nosex":
          type: file
          description: NOSEX file
          pattern: "*.{nosex}"

  - log:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.log":
          type: file
          description: LOG file
          pattern: "*.{log}"

  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@psuszyns"
maintainers:
  - "@psuszyns"
