---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "plink2_write_snplist"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "plink2_write_snplist":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Whole genome association analysis toolset"
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ['GPL v3']
      identifier:

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - bed:
        type: file
        description: BED file
        pattern: "*.bed"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - bim:
        type: file
        description: BIM file
        pattern: "*.bim"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - fam:
        type: file
        description: FAM file
        pattern: "*.fam"

  - - out_name_part:
        type: string
        description: |
          out_name_part

  - - input_args:
        type: string
        description: |
          input_args


## TODO nf-core: Add a description of all of the variables used as output
output:
  - snplist:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - "*.snplist":
        type: file
        description: snplist file
        pattern: "*.snplist"

  - id:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.id":
          type: file
          description: id file
          pattern: "*.id"

  - log:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      ## TODO nf-core: Delete / customise this example output
      - "*.log":
          type: file
          description: log file
          pattern: "*.log"

  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@psuszyns"
maintainers:
  - "@psuszyns"
