---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "qctool"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "qctool":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Command-line programs that manipulate gwas datasets and other genomic data."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ['BSL-1.0']
      identifier: biotools:qctool

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - bgen:
        type: file
        description: BGEN file
        pattern: "*.bgen"

  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - bgen:
        type: file
        description: SAMPLE file
        pattern: "*.sample"

  - - out_name_part:
        type: string
        description: |
          out_name_part

  - - input_args:
        type: string
        description: |
          input_args


## TODO nf-core: Add a description of all of the variables used as output
output:
  - bgen:
  #Only when we have meta
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - "*.bgen":
        type: file
        description: BGEN file
        pattern: "*.bgen"

  - sample:
      #Only when we have meta
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`

      - "*.sample":
          type: file
          description: SAMPLE file
          pattern: "*.sample"

  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@psuszyns"
maintainers:
  - "@psuszyns"
